INSERT INTO autor (nombre) VALUES ('NO ESPECIFICA')
INSERT INTO autor (nombre) VALUES ('SANTILLANA')
INSERT INTO autor (nombre) VALUES ('MINISTERIO DE EDUCACIÓN')
INSERT INTO autor (nombre) VALUES ('JULIO VERNE')
INSERT INTO autor (nombre) VALUES ('WILSON URTECHO RODRIGUEZ')
INSERT INTO autor (nombre) VALUES ('SYLVIANO ROCHE')
INSERT INTO autor (nombre) VALUES ('MANUEL GONZALES PRADA')

INSERT INTO categoria (nombre) VALUES ('NO ESPECIFICA')
INSERT INTO categoria (nombre) VALUES ('LIBRO')
INSERT INTO categoria (nombre) VALUES ('OBRA')
INSERT INTO categoria (nombre) VALUES ('GUIA DE APRENDIZAJE')
INSERT INTO categoria (nombre) VALUES ('SESIÓN DE APRENDIZAJE')

INSERT INTO editorial (nombre) VALUES ('NO ESPECIFICA')
INSERT INTO editorial (nombre) VALUES ('SANTILLANA')
INSERT INTO editorial (nombre) VALUES ('SAN MARCOS')
INSERT INTO editorial (nombre) VALUES ('SAN LUIS')
INSERT INTO editorial (nombre) VALUES ('SAN LUCAS')

INSERT INTO area (nombre) VALUES ('NO ESPECIFICA');
INSERT INTO area (nombre) VALUES ('MATEMÁTICA');
INSERT INTO area (nombre) VALUES ('COMUNICACIÓN');
INSERT INTO area (nombre) VALUES ('PERSONAL SOCIAL');
INSERT INTO area (nombre) VALUES ('CIENCIA Y AMBIENTE');
INSERT INTO area (nombre) VALUES ('TODAS');

INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('EDWIN', 'CABRERA', '18293123', '99988877')
INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('BRYAN', 'SANCHEZ', '18291029', '99988879')
INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('VERONICA', 'GUTIERREZ', '19028323', '99988870')
INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('FATIMA', 'LOPEZ', '19034921', '99988872')
INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('LUIS', 'MARQUEZ', '19218283', '99988873')
INSERT INTO docente (nombre, apellido, dni, telefono) VALUES ('ALAN', 'LOYOLA', '19232032', '99988874')

INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('MI-1', 'MATEMÁTICA I', 2018, 1, "DISPONIBLE", 2, 2, 2, 2)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('MI-2', 'MATEMÁTICA I', 2018, 1, "DISPONIBLE", 2, 2, 2, 2)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('MI-3', 'MATEMÁTICA I', 2018, 1, "DISPONIBLE", 2, 2, 2, 2)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('MII-1', 'MATEMÁTICA II', 2019, 2, "DISPONIBLE", 2, 2, 2, 2)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('MII-2', 'MATEMÁTICA II', 2019, 2, "DISPONIBLE", 2, 2, 2, 2)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CIII-1', 'COMUNICACIÓN III', 2020, 3, "DISPONIBLE", 3, 3, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CIII-2', 'COMUNICACIÓN III', 2020, 3, "DISPONIBLE", 3, 3, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CIV-1', 'COMUNICACIÓN IV', 2020, 4, "DISPONIBLE", 1, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CIV-2', 'COMUNICACIÓN IV', 2020, 4, "DISPONIBLE", 1, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CIV-3', 'COMUNICACIÓN IV', 2020, 4, "DISPONIBLE", 1, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('PSV-1', 'PERSONAL SOCIAL V', 2022, 5, "DISPONIBLE", 1, 3, 4, 4)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('PSV-2', 'PERSONAL SOCIAL V', 2022, 5, "DISPONIBLE", 1, 3, 4, 4)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('PSV-3', 'PERSONAL SOCIAL V', 2022, 5, "DISPONIBLE", 1, 3, 4, 4)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CAVI-1', 'CIENCIA Y AMBIENTE VI', 2021, 6, "DISPONIBLE", 2, 4, 5, 5)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CAVI-2', 'CIENCIA Y AMBIENTE VI', 2021, 6, "DISPONIBLE", 2, 4, 5, 5)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('LV-1', 'LA VUELTA AL MUNDO EN OCHENTA DIAS ', 2000, 1, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('LV-2', 'LA VUELTA AL MUNDO EN OCHENTA DIAS ', 2000, 1, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('GAI-1', 'GUIA DE APRENDIZAJE I', 2023, 1, "DISPONIBLE", 3, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('GAI-2', 'GUIA DE APRENDIZAJE I', 2023, 1, "DISPONIBLE", 3, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('GA1-3', 'GUIA DE APRENDIZAJE I', 2023, 1, "DISPONIBLE", 3, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('SAI-1', 'SESIONES DE APRENDIZAJE I', 2023, 1, "DISPONIBLE", 4, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('SAI-2', 'SESIONES DE APRENDIZAJE I', 2023, 1, "DISPONIBLE", 4, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('GAII-1', 'GUIA DE APRENDIZAJE II', 2023, 2, "DISPONIBLE", 3, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('GAII-2', 'GUIA DE APRENDIZAJE II', 2023, 2, "DISPONIBLE", 3, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('SAII-1', 'SESIONES DE APRENDIZAJE II', 2022, 2, "DISPONIBLE", 4, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('SAII-2', 'SESIONES DE APRENDIZAJE II', 2022, 2, "DISPONIBLE", 4, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('SAII-3', 'SESIONES DE APRENDIZAJE II', 2022, 2, "DISPONIBLE", 4, 5, 1, 6)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('ATI-1', 'ALGO TE IDENTIFICA', 2007, 4, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('ATI-2', 'ALGO TE IDENTIFICA', 2007, 4, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('ATI-3', 'ALGO TE IDENTIFICA', 2007, 4, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CET-1', 'CREO EN TI', 2005, 5, "DISPONIBLE", 2, 2, 3, 3)
INSERT INTO libro (codigo, titulo, anio, grado, estado, autor_id, categoria_id, editorial_id, area_id) VALUES ('CET-2', 'CREO EN TI', 2005, 5, "DISPONIBLE", 2, 2, 3, 3)

INSERT INTO prestamo_libro (fecha_prestamo, fecha_limite, grado, seccion, estado, docente_id) VALUES (NOW(), '2023-06-15 19:30:00', 1, 'A', 'PENDIENTE', 1)
INSERT INTO prestamo_libro (fecha_prestamo, fecha_limite, grado, seccion, estado, docente_id) VALUES (NOW(), '2023-06-15 19:30:00', 2, 'B', 'PENDIENTE', 1)
INSERT INTO prestamo_libro (fecha_prestamo, fecha_limite, grado, seccion, estado, docente_id) VALUES (NOW(), '2023-06-15 19:30:00', 3, 'C', 'PENDIENTE', 1)

INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (1, 1)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (2, 1)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (3, 1)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (4, 2)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (5, 2)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (6, 3)
INSERT INTO detalle_prestamo_libro (libro_id, prestamo_libro_id) VALUES (7, 3)

INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('JARRAS MEDIDORAS', 39, 1)
INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('DADOS NUMÉRICOS', 20, 1)
INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('CALCULADORAS', 90, 1)
INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('FICHAS DE DIFERENTES TIPOS DE LETRAS', 32, 2)
INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('IMANES', 21, 4)
INSERT INTO material (nombre, cantidad_inicial, area_id) VALUES ('LUPAS', 6, 4)